### ISSUE TITLE
Curso da Udemy

### ISSUE THREAD

**Issue by zekicarvalho** [adrianoleitedasilva/most-used-words#1]
Esse é o mesmo leitor de legendas desse curso da [Udemy](https://www.udemy.com/course/aplicacao-desktop-com-javascript-electron-js-e-vue-js/learn/) ou tem alguma modificação?

**Comment by adrianoleitedasilva** [comment]
Zeki, tem modificações visuais apenas(cores, paddings e margins).

**Comment by zekicarvalho** [comment]
@adrianoleitedasilva vlw, tava procurando por isso.

**Comment by adrianoleitedasilva** [comment]
Ahhhh legal meu caro... fique a vontade para clonar o repo. Se tiver alguma sugestão de melhoria, estou por aqui para ouvir. 

Forte abraço.

**Comment by adrianoleitedasilva** [comment]
Questão respondida...
